# Generated by Django 2.1.5 on 2019-01-26 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 3, 1, 56, 193916, tzinfo=utc)),
        ),
    ]
