# Generated by Django 2.1.5 on 2019-01-26 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190126_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 26, 3, 37, 34, 905505, tzinfo=utc)),
        ),
    ]
